package com.ssm.entity;

public class Performance {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column performance.performance
     *
     * @mbg.generated
     */
    private Float performance;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance.id
     *
     * @return the value of performance.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance.id
     *
     * @param id the value for performance.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column performance.performance
     *
     * @return the value of performance.performance
     *
     * @mbg.generated
     */
    public Float getPerformance() {
        return performance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column performance.performance
     *
     * @param performance the value for performance.performance
     *
     * @mbg.generated
     */
    public void setPerformance(Float performance) {
        this.performance = performance;
    }
}