package com.ssm.entity;

import java.util.Date;

public class Tours_group {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tours_group.groud_id
     *
     * @mbg.generated
     */
    private Integer groudId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tours_group.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tours_group.route_id
     *
     * @mbg.generated
     */
    private Integer routeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tours_group.guide_id
     *
     * @mbg.generated
     */
    private Integer guideId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tours_group.total_people
     *
     * @mbg.generated
     */
    private Integer totalPeople;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tours_group.total_price
     *
     * @mbg.generated
     */
    private Float totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tours_group.start_date
     *
     * @mbg.generated
     */
    private Date startDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tours_group.groud_id
     *
     * @return the value of tours_group.groud_id
     *
     * @mbg.generated
     */
    public Integer getGroudId() {
        return groudId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tours_group.groud_id
     *
     * @param groudId the value for tours_group.groud_id
     *
     * @mbg.generated
     */
    public void setGroudId(Integer groudId) {
        this.groudId = groudId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tours_group.user_id
     *
     * @return the value of tours_group.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tours_group.user_id
     *
     * @param userId the value for tours_group.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tours_group.route_id
     *
     * @return the value of tours_group.route_id
     *
     * @mbg.generated
     */
    public Integer getRouteId() {
        return routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tours_group.route_id
     *
     * @param routeId the value for tours_group.route_id
     *
     * @mbg.generated
     */
    public void setRouteId(Integer routeId) {
        this.routeId = routeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tours_group.guide_id
     *
     * @return the value of tours_group.guide_id
     *
     * @mbg.generated
     */
    public Integer getGuideId() {
        return guideId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tours_group.guide_id
     *
     * @param guideId the value for tours_group.guide_id
     *
     * @mbg.generated
     */
    public void setGuideId(Integer guideId) {
        this.guideId = guideId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tours_group.total_people
     *
     * @return the value of tours_group.total_people
     *
     * @mbg.generated
     */
    public Integer getTotalPeople() {
        return totalPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tours_group.total_people
     *
     * @param totalPeople the value for tours_group.total_people
     *
     * @mbg.generated
     */
    public void setTotalPeople(Integer totalPeople) {
        this.totalPeople = totalPeople;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tours_group.total_price
     *
     * @return the value of tours_group.total_price
     *
     * @mbg.generated
     */
    public Float getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tours_group.total_price
     *
     * @param totalPrice the value for tours_group.total_price
     *
     * @mbg.generated
     */
    public void setTotalPrice(Float totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tours_group.start_date
     *
     * @return the value of tours_group.start_date
     *
     * @mbg.generated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tours_group.start_date
     *
     * @param startDate the value for tours_group.start_date
     *
     * @mbg.generated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
}