package com.ssm.dao;

import java.util.List;

import com.ssm.entity.Performance;

public interface PerformanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance
     *
     * @mbg.generated
     */
    int insert(Performance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance
     *
     * @mbg.generated
     */
    int insertSelective(Performance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance
     *
     * @mbg.generated
     */
    Performance selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Performance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table performance
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Performance record);
}