package com.ssm.dao;

import com.ssm.entity.Tours_route;

public interface Tours_routeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tours_route
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tours_route
     *
     * @mbg.generated
     */
    int insert(Tours_route record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tours_route
     *
     * @mbg.generated
     */
    int insertSelective(Tours_route record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tours_route
     *
     * @mbg.generated
     */
    Tours_route selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tours_route
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Tours_route record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tours_route
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Tours_route record);
}