package com.ssm.dao;

import com.ssm.entity.Tours_guide;

public interface Tours_guideMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tours_guide
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer guideId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tours_guide
     *
     * @mbg.generated
     */
    int insert(Tours_guide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tours_guide
     *
     * @mbg.generated
     */
    int insertSelective(Tours_guide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tours_guide
     *
     * @mbg.generated
     */
    Tours_guide selectByPrimaryKey(Integer guideId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tours_guide
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Tours_guide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tours_guide
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Tours_guide record);
}