package com.ssm.dao;

import com.ssm.entity.Tours_group;

public interface Tours_groupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tours_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer groudId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tours_group
     *
     * @mbg.generated
     */
    int insert(Tours_group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tours_group
     *
     * @mbg.generated
     */
    int insertSelective(Tours_group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tours_group
     *
     * @mbg.generated
     */
    Tours_group selectByPrimaryKey(Integer groudId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tours_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Tours_group record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tours_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Tours_group record);
}